const SAFE_METHODS = new Set(["GET", "HEAD", "OPTIONS"])
const KNOWN_FETCH_SITES = new Set(["cross-site", "same-origin", "same-site", "none"])
const SESSION_COOKIE_NAMES = [
  "next-auth.session-token",
  "__Secure-next-auth.session-token",
  "authjs.session-token",
  "__Secure-authjs.session-token",
]

export function hasSessionCookie(cookieHeader: string | null): boolean {
  if (!cookieHeader) return false
  return SESSION_COOKIE_NAMES.some((name) => cookieHeader.includes(`${name}=`))
}

export function isCookieAuthenticatedMutationAllowed(input: {
  method: string
  requestUrl: string
  origin: string | null
  secFetchSite: string | null
  cookieHeader: string | null
}): boolean {
  if (SAFE_METHODS.has(input.method.toUpperCase())) return true
  if (!hasSessionCookie(input.cookieHeader)) return true

  // Fetch Metadata is generated by the browser from the public request context.
  // Prefer it when available because requestUrl can contain an internal origin
  // after a reverse proxy or CDN has forwarded the request to Next.js.
  const fetchSite = input.secFetchSite?.toLowerCase()
  if (fetchSite === "same-origin") return true
  if (fetchSite && KNOWN_FETCH_SITES.has(fetchSite)) return false

  // Older clients may not send Fetch Metadata, so retain the strict Origin
  // comparison as a backwards-compatible fallback.
  if (input.origin) {
    try {
      return new URL(input.origin).origin === new URL(input.requestUrl).origin
    } catch {
      return false
    }
  }

  return false
}

export function requestBodyLimitForPath(pathname: string): number {
  if (pathname === "/api/v1/upload/image") return 5 * 1024 * 1024
  if (pathname.includes("/import")) return 3 * 1024 * 1024
  if (pathname === "/api/v1/admin/global-inventory") return 7 * 1024 * 1024
  if (pathname.startsWith("/api/v1/inventory/global-products/")) return 7 * 1024 * 1024
  return 1024 * 1024
}

export function isKnownBodyTooLarge(contentLength: string | null, maximumBytes: number): boolean {
  if (!contentLength || !/^\d+$/.test(contentLength)) return false
  const parsed = Number(contentLength)
  return Number.isSafeInteger(parsed) && parsed > maximumBytes
}
